# Generated by Django 5.2.5 on 2025-08-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_blog_website_post_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='blog_website',
        ),
    ]
